#!/usr/bin/env bash

# Print an error message and exit.
panic()
{
	echo "ERROR: $@"
	exit 1
}

# Get the directory in which the currently running script is located.
cmd_dir=$(dirname "$0") || panic "cannot determine command directory"

#Get main_program
main_program="$cmd_dir/main"

echo "Running main program"
$main_program || panic "main program failed"
